datastore:
  image: busybox
  volumes:
      - /opt/datastore:/var/lib/mysql
  container_name: la5-datastore
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: pass
  ports:
    - "3306:3306"
  volumes_from:
    - datastore
  container_name: la5-mysql
php:
  build: ./php
  ports:
    - "8099:80"
  volumes:
    -  /Users/horie/work/hoge:/var/www/jf
  links:
    - mysql:la5-mysql
  container_name: la5-php
